language:
  - python

python:
  - "3.4"

before_install:
  - sudo apt-get -y install python-software-properties software-properties-common
  - sudo DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:ondrej/php5-oldstable
  - sudo apt-get update -qq
  - sudo apt-get install -qq php5-cli php5-sqlite
  - nohup bash -c "cd server/; php -S 127.0.0.1:8080" &

install:
  - pip install -r client/requirements.txt
  - bash -c "cd client/; python setup.py install"

script:
  - bash -c "cd server/; php -v; php -S 127.0.0.1:8080"
  - bash -c "cd client/; bush -u http://localhost:8080/ up requirements.txt; bush -u http://localhost:8080/ ls"
