language:
  - python

python:
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install python-software-properties software-properties-common tree
  - echo 'yes' | sudo add-apt-repository ppa:ondrej/php5-oldstable
  - sudo apt-get update -qq
  - sudo apt-get install -qq php5-cli php5-sqlite

install:
  - pip install -r client/requirements.txt
  - bash -c "cd client/; python setup.py install"
  - mkdir -p $HOME/.config/bush/
  - echo 'url\: http://127.0.0.1:8080/' > $HOME/.config/bush/config.yaml
  - nohup bash -c "cd server/; php -S 127.0.0.1:8080" &

script:
  - bush up client/requirements.txt
  - bush ls | grep requirements | grep requirements.txt
  - tests/client_up.sh
  - sqlite3 server/data/files.sqlite 'select * from files where tag = "requirements"' | wc -l | grep -e '^1$'
